# Generated by Django 5.1.1 on 2024-10-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceControl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deviceactions',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deviceactions',
            name='toggled',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
