# Generated by Django 5.1.1 on 2024-10-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceControl', '0002_alter_device_created_date_alter_device_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='DeviceActions',
        ),
    ]
