# Generated by Django 4.2.16 on 2024-11-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceControl', '0006_devicegroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicegroup',
            name='device_list',
        ),
        migrations.AddField(
            model_name='devicegroup',
            name='device_list',
            field=models.ManyToManyField(related_name='device_list', to='deviceControl.device'),
        ),
    ]
