# Generated by Django 4.2.16 on 2024-11-01 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deviceControl', '0007_remove_devicegroup_device_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicegroup',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_group_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DeviceScenario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
                ('action', models.CharField(choices=[('activate', 'Activate'), ('deactivate', 'Deactivate')], default='activate', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_scenario_created_by', to=settings.AUTH_USER_MODEL)),
                ('device_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_group', to='deviceControl.devicegroup')),
            ],
        ),
    ]
